version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: 
        name: Build image 
        command: |
            docker build -f docker/Dockerfile -t autoct:$CIRCLE_BRANCH .
     - run: 
        name: Run Tests
        command: |
            mkdir test-results
            chmod 777 test-results
            docker run --rm -v $(pwd):/testing -w /testing -it autoct:$CIRCLE_BRANCH pytest --junitxml=test-results/junit.xml tests 
        no_output_timeout: 40m

     - store_test_results:
        path: test-results

     - store_artifacts:
        path: test-results 
